# Introduction

Tools and capabilities of data science is changing everyday but it is simply making data work for you. Data can:
- Describe the current state of an organization or process
- Detec anomalous events
- Diagnose the causes of events and behaviors
- Predict future events

Data Science workflow includes:
- Data collection
- Exploration and visualization
- Experimentation and prediction

Applications of data science:
- Traditional machine learning: e.g. finding probabilities of events, labeled data, and algorithms
- Deep learning: neurons work together for image and natural language recognition but requires more training data
- Internet of things (IOT): e.g. smart watch algorithms to detect and analyze motion sensors

Building a data science team:
- Data engineers: SQL, Java, Scala, Python
- Data analysts: Dashboards, hypothesis tests and visualization using spreadsheets, SQL, BI (Tableau, power BI, looker)
- Machine learning scientists: predictions and extrapolations, classification, etc. and use R or python
Data employees can be isolated, embedded, or hybrid.

Data sources and risks [Data collection phase of data science workflow]:
(Consider GDPR [General Data Protection Regulation] policies for personally identifiable information which needs to treated with sensitivity and caution through data pseudonymization and anonymization)
- web events
- customer data (solicited): surveys, reviews, focus groups, in-app questions
- logistics data
- financial transactions

Data can be qualitative or quantitative. 
Preferences can be stated or revealed through the data so questions need to be specific, avoid loaded language, calibrate, require actionable results.

Data storage and retrieval: 
- parallel storage solutions (e.g. cluster or server)
- cloud storage (google, amazon, azure)
- types of data: 1) unstructured (email, text, video, audio, web, and social media = document database); 2) structured = relational databases
- Data querying: NoSQL and SQL 

Communication of data using: 
- Dashboards:
- build using spreadsheets 
- BI tools
- rshiny or d3.js

Ad hoc analysis
- can use ticketing system such as Trello or JIRA to communicate due data and priority

A/B Testing:
- Control and Variation in samples
- 4 steps in A/B testing: pick metric to track, calculate sample size, run the experiment, and check significance 

Machine learning:  
Supervised: labels and features
- recommendation systems
- subscription predictions
- email subject optimization

# Getting Set-Up with R & RStudio
