`r if (knitr::is_html_output()) '
# Resources {-}
'`

***

## Beginner Resources by Topic

***

### Getting Set-Up with R & RStudio

* __Download & Install R:__
    + https://cran.r-project.org
    + For Mac: click on **Download R for (Mac) OS X**, look at the top link under **Files**, which at time of writing is **R-3.2.4.pkg**, and download this if compatible with your current version mac OS (Mavericks 10.9 or higher). Otherwise download the version beneath it which is compatible for older mac OS versions. Then install the downloaded software.
    + For Windows: click on **Download R for Windows**, then click on the link **install R for the first time**, and download from the large link at the top of the page which at time of writing is **Download R 3.2.4 for Windows**. Then install the downloaded software.
    
* __Download & Install RStudio:__
    + https://www.rstudio.com/products/rstudio/download/
    + For Mac: under the **Installers for Supported Platforms** heading click the link with **Mac OS X** in it. Install the downloaded software.
    + For Windows: under the **Installers for Supported Platforms** heading click the link with **Windows Vista** in it. Install the downloaded software.
    


* __Exercises in R: swirl (HIGHLY RECOMMENDED):__
    + http://swirlstats.com/students.html
    
    
* __Data Prep__:
    + Intro to dplyr: https://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html
    + Data Manipulation (detailed): http://www.sr.bham.ac.uk/~ajrs/R/index.html
    + Aggregation and Restructing Data (base & reshape): http://www.r-statistics.com/2012/01/aggregation-and-restructuring-data-from-r-in-action/
* **Data Types intro**: Vectors, Matrices, Arrays, Data Frames, Lists, Factors: http://www.statmethods.net/input/datatypes.html
* **Using Dates and Times**: http://www.cyclismo.org/tutorial/R/time.html
* **Text Data and Character Strings**: http://gastonsanchez.com/Handling_and_Processing_Strings_in_R.pdf
* **Data Mining**: http://www.rdatamining.com  

****

* **Data Viz**:
    + ggplot2 Cheat Sheet (RECOMMENDED): http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/
    + ggplot2 theoretical tutorial (detailed but RECOMMENDED): http://www.ling.upenn.edu/~joseff/avml2012/
    + Examples of base R, ggplot2, and rCharts: http://patilv.com/Replication-of-few-graphs-charts-in-base-R-ggplot2-and-rCharts-part-1-base-R/
    + Intro to ggplot2: http://heather.cs.ucdavis.edu/~matloff/GGPlot2/GGPlot2Intro.pdf
* **Interactive Visualisations**:
    + Interactive graphics (rCharts, jQuery): http://www.computerworld.com/article/2473365/business-intelligence/business-intelligence-106897-how-to-turn-csv-data-into-interactive-visualizations-with-r-and-rchart.html    

*****

* **Statistics**:  
    + Detailed Statistics Primer: http://health.adelaide.edu.au/psychology/ccs/docs/lsr/lsr-0.3.pdf
    + Beginner guide to statistical topics in R: http://www.cyclismo.org/tutorial/R/
* **Linear Models**: http://data.princeton.edu/R/gettingStarted.html
* **Time Series Analysis**: https://www.otexts.org/fpp/resources
* **Little Book of R series**:
    + Time Series: http://a-little-book-of-r-for-time-series.readthedocs.org/en/latest/
    + Biomedical Statistics: http://a-little-book-of-r-for-biomedical-statistics.readthedocs.org/en/latest/
    + Multivariate Statistics: http://little-book-of-r-for-multivariate-analysis.readthedocs.org/en/latest/

***
* **RStudio Cheat Sheets**:
    + RStudio IDE: http://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf
    + Data Wrangling (dplyr & tidyr): https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
    + Data Viz (ggplot2): https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf
    + Reproducible Reports (markdown): https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf
    + Interactive Web Apps (shiny): https://www.rstudio.com/wp-content/uploads/2015/02/shiny-cheatsheet.pdf  
    
***
### Specialist Topics

* __Google Analytics__: http://online-behavior.com/analytics/r
* **Spatial Cheat Sheet**: http://www.maths.lancs.ac.uk/~rowlings/Teaching/UseR2012/cheatsheet.html
* **Translating between R and SQL**: http://www.burns-stat.com/translating-r-sql-basics/
* **Google's R style guide**: https://google.github.io/styleguide/Rguide.xml

***

### Operational Basics

* **Working Directory**:  
Example on a mac = `setwd("~/Desktop/R")` or `setwd("/Users/CRT/Desktop/R")`         
Example on windows = `setwd("C:/Desktop/R")`       
* **Help**:  
`?functionName`   
`example(functionName)`   
`args(functionName)`   
`help.search("your search term")`   
* **Assignment Operator**: `<-`   

***

